name: Build Artifacts

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6
          cache-read-only: false
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"
      - name: Set env
        run: |
          git config --global user.email "ci@noreply.example.com"
          git config --global user.name "github_actions"
          echo "RELEASE_TAG=${GITHUB_REF_NAME}-build" >> $GITHUB_ENV
          echo "RELEASE_TAG=${GITHUB_REF_NAME}-build"
          echo "RELEASE_VERSION=$(date +'%Y.%m.%d').X${GITHUB_RUN_NUMBER}-${GITHUB_REF_NAME}" >> $GITHUB_ENV
          
          echo "${{ secrets.KEYSTORE_BASE64 }}" | openssl enc -d -base64 -in - -out bekeystore.jks
      - name: Build
        env:
          keystore_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias_password: ${{ secrets.KEYSTORE_PASSWORD_SECRET }}
          keystore_alias: MindustryX
        run: |
          git submodule update --init --depth=10
          cd work
          ../scripts/applyPatches.sh
          sed -i 's/tinylake.mindustryX/tinylake.mindustryX.be/g' android/build.gradle
          sed -i 's/MindustryX/MindustryX BE/g' android/res/values/strings.xml
          gradle -Pbuildversion=${RELEASE_VERSION} --parallel \
            desktop:dist server:dist android:assembleRelease 
          
          cd ..
          mkdir artifacts
          mv work/desktop/build/libs/Mindustry.jar artifacts/MindustryX-${{env.RELEASE_VERSION}}-Desktop.jar
          mv work/server/build/libs/server-release.jar artifacts/server-${{env.RELEASE_VERSION}}.jar
          mv work/android/build/outputs/apk/release/android-release.apk artifacts/MindustryX-${{env.RELEASE_VERSION}}-Android.apk
#      - name: Update Tag
#        uses: rickstaa/action-create-tag@v1
#        with:
#          tag: ${{ env.RELEASE_TAG }}
#          force_push_tag: true
      - name: Release
        uses: softprops/action-gh-release@v2.0.2
        with:
          repository: TinyLake/MindustryX-work
          token: ${{secrets.PUBLISH_TOKEN}}
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_VERSION }}
          target_commitish: ${{github.sha}}
          files: artifacts/*
          prerelease: true
      - uses: oven-sh/setup-bun@v1
      - name: clearOldAssets
        run: bun run .github/actions/clearOldAssets.ts
        env:
          TOKEN: ${{secrets.PUBLISH_TOKEN}}
          REPOSITORY: TinyLake/MindustryX-work
          TAG: ${{ env.RELEASE_TAG }}
